### ISSUE TITLE
bug: Pigeon is consuming 30,000 eth get_logs request per day. This is expensive!

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#313]
# What is happening?
Pigeon is consuming 30,000 eth get_logs request per day. This is expensive for endpoints. 

# How to reproduce?
Standard running of Pigeon service is consuming 30,000 requests per day. The costs on bandwith and usage may not be sustainable for a large flock.

# What is the expected behaviour?
Are we able to optimize on this level of requests? Should we query a contract vs. block?

**Comment by Vizualni** [comment]
Given that we instructed pigeons to run local eth node this is not doing any harm to a "global" eth network. This results (on average) about 20 requests per minute. Those requests are quite lightweight and do not cause any harm + the logs that pigeons are fetching are also indexed nicely on the eth side. There are at least 3 optimizations that I see that we can do to improve. Going to write them down so I don't forget.

- increase the loop delay to a 1 minute
- use chain info that we get from paloma and use the provided block height as a starting point to query the logs (internal)
- use local caching so that we don't have to hit eth endpoints (need to see at what extent we can do this)

**Comment by D-Elektra** [comment]
So do we have to set up the local ETH node and there is no way to use endpoints?

**Comment by taariq** [comment]
@D-Elektra you will need to broadcast txes so whatever approach is really up to you. You can either use your own node or an  endpoint.

**Comment by D-Elektra** [comment]
@taariq ok so I will shoot 2 more important questions and set you free.
1. Is it has to be an archive node?
2. Tracing required or not?

**Comment by taariq** [comment]
> 

Pigeons will be required to broadcast messages to the mainnet. It's a message relay network. An archive node will not be sufficient. Tracing is not required in this moment, but we will see what happens in the future!

Now I fly away!

**Comment by Vizualni** [comment]
This was improved even at https://github.com/palomachain/pigeon/pull/42. Closing.
