### ISSUE TITLE
BUG: Validator is not receiving refunds for her ETH and BNB

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#534]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Again jailed.
[0xBaE919E4B272193544A9f18aF1fB75F918D2B1F0](https://etherscan.io/address/0xBaE919E4B272193544A9f18aF1fB75F918D2B1F0#internaltx) balance is low 0.04 ETH
[https://bscscan.com/address/0x0Ba5F0e6BDbc820EC58BC44f9c96A8A515Fb8Cfc#internaltx](https://bscscan.com/address/0x0Ba5F0e6BDbc820EC58BC44f9c96A8A515Fb8Cfc#internaltx) balance 0.04 BNB

Balances are not being refunded by the vyper contracts.

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

N/A

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

run.py and run_bsc.py do not make payments to the validator addresses.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

0xBaE919E4B272193544A9f18aF1fB75F918D2B1F0 should have refunds.
0x0Ba5F0e6BDbc820EC58BC44f9c96A8A515Fb8Cfc should have refunds

**Comment by fieldtheory123** [comment]
This turns out to be a timing mismatch, and a general issue when balance checking takes place before a validator is given refund. 

For this particular case, here is what happened:
1. [around 18:52] at [15733935](https://etherscan.io/block/15733935), the user received refund (https://etherscan.io/tx/0x7ae52beab7991863321352fa489c3152c3f751c69abee3a529114b0b222bc66c) and the balance was sufficient 
2. [around 23:05] at [15735200](https://etherscan.io/block/15735200), the user signed a valset update and spent some ETH, leading the balance to be less than 0.05ETH
3. [at 00:00] balance checking took place which led the user to be jailed [big assumption: balance checking happens at 00:00 UTC, need to be confirmed]

If the assumption is correct, the current problem can be resolved by running gas refund right before 00:00 UTC every day.

**Comment by taariq** [comment]
@fieldtheory123 
Sergio | PPNV Service, [Oct 13, 2022 at 5:16:40 AM (Oct 13, 2022 at 5:20:40 AM)]:
hey man!
my eth balance <0.05eth

time="2022-10-13T12:16:31+02:00" level=info msg="not staking. waiting"

https://etherscan.io/address/0x279fC7c0ebEf3328d3899FE73464347A764C5f2C

**Comment by verabehr** [comment]
@fieldtheory123 @taariq according to the pigeon video (~minute 6:30) balance check happens "every 5 minutes or so" for all alive pigeons. So I think this needs to be run on a cron job.

**Comment by verabehr** [comment]
On second thought, if we run the refunds more often our gas costs will also go up. So it might make more sense to increase the refund amount, so pigeons balances last longer before they hit the threshold again. 
@fieldtheory123 by how much would we need to increase the refund amount OR how often would we need to run the refund script to ensure pigeons don't run out of gas given our current txs volume?

**Comment by fieldtheory123** [comment]
I think we need to come up with a way to preemptively give refund to avoid pigeons getting jailed, also taking gas cost into consideration. I've had some ideas and will write something up.

**Comment by taariq** [comment]
Fixed with automated refunds.
