### ISSUE TITLE
Nodes unable to catch-up due to valset snapshot get and store requests hitting 300x per second.

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#654]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Node can't catch up, basically it consumes old blocks with the same frequency as the chain produces new blocks. After investigation, we notice that the INFORMATION logs are showing the following calls occurring about 300 times per second. Submitted user logs are here: https://github.com/palomachain/paloma/blob/master/x/valset/keeper/keeper.go#L363 and a section is below.

```
Jan 16 18:37:47 paloma palomad[1202129]: 6:37PM INF snapshot store module=x/valset store-key-name=valset store-key-string="KVStoreKey{0xc000f749e0, valset}"
Jan 16 18:37:47 paloma palomad[1202129]: 6:37PM INF get current snapshot last-id=7925 module=x/valset snapshot-validator-size=2
Jan 16 18:37:47 paloma palomad[1202129]: 6:37PM INF snapshot store module=x/valset store-key-name=valset store-key-string="KVStoreKey{0xc000f749e0, valset}"
Jan 16 18:37:47 paloma palomad[1202129]: 6:37PM INF get current snapshot last-id=7925 module=x/valset snapshot-validator-size=2
Jan 16 18:37:47 paloma palomad[1202129]: 6:37PM INF snapshot store module=x/valset store-key-name=valset store-key-string="KVStoreKey{0xc000f749e0, valset}"
```
The functions for these logs are:
**get current snapshot:** https://github.com/palomachain/paloma/blob/master/x/valset/keeper/keeper.go#L363
**valset store:** https://github.com/palomachain/paloma/blob/master/x/valset/keeper/keeper.go#L510

The snapshots are triggered in the keeper.go here:
**Build a Snapshot** https://github.com/palomachain/paloma/blob/master/x/valset/keeper/keeper.go#L171

We believe that a bad BNB smart contract deployment is causing the system to try to deploy the contract and is requesting these valsets and storing them in some type of race condition.

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Paloma v.011.5 
Pigeon v0.11.5

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

The snapshot frequency should be much less, possibly once per minute allowing validors to sync blocks faster than 5 seconds per block

**Comment by alipostaci2001** [comment]
later update logs :  https://gist.github.com/alipostaci2001/9ff07b1cedc20bf4b7e99ba920574556

later state_sync : https://gist.github.com/alipostaci2001/bce07ba81b87eb8da254c0430b6f5d70

**Comment by VitaValeriya** [comment]
Paloma:
version: v0.11.5
commit: 141b17e0a40ae8cd019c49e5307ba11240dcd122
Pigeon:
App version: v0.11.5
Build commit hash: cd14972b74003d3613963f552752e6bcde826fe4
Palomad logs https://gist.github.com/VitaValeriya/0e7126b3d7e74d65aecea5d793832c2c

**Comment by taariq** [comment]
Attempts to Unjail are failing: https://paloma.explorers.guru/transaction/E7F3A02F798A645978B6BF6DA580FA57D3589FBACC096BF0BB75CDE784E350FE

**Comment by alexanderbez** [comment]
> Node can't catch up, basically it consumes old blocks with the same frequency as the chain produces new blocks.

From the NG explorer, it seems the average block time is ~6.x seconds. This is plenty reasonable for nodes to sync and eventually catch up (assuming peering is sufficient).

So my guess is that they're never able to catch up due to the fact that when they're processing old blocks, they're burdened with these endless snapshot calls as you've pointed out?

I looked at all the places where `GetCurrentSnapshot ` is called:

- `TriggerSnapshotBuild`
- `GetSnapshotByID`
- `CheckExternalBalancesForChain`
- `deploySmartContractToChain`
- `findEvidenceThatWon`
- `GetMessagesThatHaveReachedConsensus`

Of these, `TriggerSnapshotBuild` and `CheckExternalBalancesForChain` are called each `EndBlock`. `CheckExternalBalancesForChain` calls `GetCurrentSnapshot` for each `ChainInfo`, but I doubt there's 300+ chain infos? Right?

In any case, I don't think that it's due to those that are called at `EndBlock`. So that leaves:

- `deploySmartContractToChain`
- `findEvidenceThatWon`

I took a look at who/when these are called and boiled it down to:

- `TryDeployingLastSmartContractToAllChains`
- `SaveNewSmartContract`
- `attestValidatorBalances`
- `attestRouter`

So what I would recommend is adding logs to these calls to see who is triggering `GetCurrentSnapshot` so many times. This will give us clues as to where to debug further...

----


> Attempts to Unjail are failing: https://paloma.explorers.guru/transaction/E7F3A02F798A645978B6BF6DA580FA57D3589FBACC096BF0BB75CDE784E350FE

You need to query for that validator's jailing info in the x/slashing module. You cannot unjail until the unjail time has expired. Query the x/slashing module for the exact details. There is a query for this: `/cosmos/slashing/v1beta1/signing_infos/{cons_address}`

**Comment by verabehr** [comment]
Thanks @alexanderbez . 
We actually see a lot of logs related to `attestValidatorBalances` on the birdpoop2 machine. These are level `debug`. See this example screenshot. I've scanned through a bunch, they are all the same type, `typeurl: /palomachain.paloma.evm.ValidatorBalancesAttestation` but with different `MESSAGE.id`
<img width="1366" alt="Screen Shot 2023-01-16 at 5 17 16 PM" src="https://user-images.githubusercontent.com/19958639/212773561-c03a8e18-ba38-481f-9d76-f34e0c0b900c.png">

**Comment by alexanderbez** [comment]
Thanks @verabehr, that's super helpful.

So it seems that there are a ton of `ValidatorBalancesAttestation` messages in the queue for which `attestValidatorBalances` is called....which makes sense.

So then the question becomes, what is putting so many of these messages into the queue? Is this amount normal? 

Based on a quick scan, and correct me if I'm wrong, but it seems `CheckExternalBalancesForChain` is responsible for putting these messages there? But again, that loops over chain infos and surely there can't be 300 of them right?

**Comment by verabehr** [comment]
No, there is only 2 chains in `chains-infos`

**Comment by taariq** [comment]
Conclusion of possible issue: 

1. Queued messages for Paloma are stored on chain.
2. The Paloma chain is simply overwhelmed with messages that have been occurring for quite some time due to failed valset updates 
3. Those failed queued messages were never handled in the upgrade to v0.11.5
4. Therefore, they are now able to be handled and now they have a huge backlog to process.
5. In other words, these messages are not handled for a while, and now all of a sudden are being handled all at once.

Next steps: 
1. Add UpgradeHndler to delete queued messages during upgrade
2. Launch a new network on testnet without the backlog
3. Closing this ticket as we will launch a new network and put up a new ticket to clear Queues when palomachain is undergoing a breaking change upgrades.

**Comment by taariq** [comment]
Closing for now with plan to switch to validator key for relaying.
