### ISSUE TITLE
bug: BNB mainnet evidence of contract deployment fails with account sequence mismatch

### ISSUE THREAD

**Issue by verabehr** [palomachain/paloma#681]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Compass EVM is deployed to BNB Mainnnet as expected, but when the pigeon account that deployed the contract is trying to provide the evidence that the contract was deployed to Paloma an account sequence mismatch error happens. 

See the logs here https://gist.github.com/alipostaci2001/c7868cca40d66bedb8e9ef9c7ecbc4ff#file-pigeon-logs-25-01-2023-paloma-L30-L31

This error comes from here https://github.com/palomachain/pigeon/blob/master/relayer/process.go#L122

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

paloma v0.11.6
pigeon v.0.11.5

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

{WRITE YOUR ANSWER HERE}

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

It seems like the process is happening to soon and should wait for the next block? 
Ultimately, we don't want the account sequence mismatch error to happen

**Comment by alexanderbez** [comment]
Yeah this happens when the sending/singing process is not in sync (i.e. it's behind) or is trying to submit a lot of txs at once. 

This problem, while in theory should not happen as `CheckTx` should prevent such txs from entering the mempool, it still happens on mainnet nodes.

I will say, that it will/can be easily mitigated with ABCI++ in SDK v0.47, where you can explicitly check for these txs.

In any case, until you're on SDK v0.47, for the time being, it's best to ensure the pigeon process (or whatever process is responsible) is synced completely and not sending multiple txs at the same time.

**Comment by verabehr** [comment]
closing, we have a potential duplicate issue already
